apiVersion: v1
kind: PersistentVolume
metadata:
  name: koji-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /volumes/koji-volume
